language: java
jdk:
  - oraclejdk8

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

git:
  depth: 3
env:
  matrix:
    - GRADLE_OPTS="-Xms1g -Xmx3g"
install: true
script: "gradle build --refresh-dependencies"
addons:
  apt:
    packages:
      - oracle-java8-installer
