version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat build

cache:
  - C:\Users\appveyor\.gradle

artifacts:
  - path: prison-spigot\build\libs\Prison.jar

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true
